"""
Incident Reporter Lambda

Triggered by SNS when CloudWatch alarms fire.
Uses Claude via Bedrock to analyze incidents and generate summaries.
"""

import json
import os
import boto3
from datetime import datetime
from claud import invoke_claude

# Environment variables
CLAUDE_MODEL = os.environ.get("CLAUDE_MODEL", "anthropic.claude-3-haiku-20240307-v1:0")
SNS_TOPIC_ARN = os.environ.get("SNS_TOPIC_ARN", "")

sns = boto3.client("sns")

SYSTEM_PROMPT = """You are a Site Reliability Engineer (SRE) analyzing infrastructure incidents.
When given CloudWatch alarm data, provide:

1. **Incident Summary** - One sentence describing what happened
2. **Severity Assessment** - LOW/MEDIUM/HIGH/CRITICAL based on impact
3. **Probable Cause** - Most likely reason for the alarm
4. **Immediate Actions** - 2-3 steps to investigate or mitigate
5. **Runbook Reference** - Suggest relevant runbook or documentation

Be concise and actionable. Use bullet points."""


def handler(event, context):
    """
    Lambda handler for incident reporting.

    Expects SNS event from CloudWatch alarm.
    """
    print(f"Received event: {json.dumps(event)}")

    for record in event.get("Records", []):
        if record.get("EventSource") == "aws:sns":
            process_sns_record(record)

    return {"statusCode": 200, "body": "Processed"}


def process_sns_record(record):
    """Process a single SNS record containing CloudWatch alarm data."""
    sns_message = record.get("Sns", {})
    message_str = sns_message.get("Message", "{}")

    try:
        alarm_data = json.loads(message_str)
    except json.JSONDecodeError:
        # Message might be plain text
        alarm_data = {"RawMessage": message_str}

    # Extract alarm details
    alarm_name = alarm_data.get("AlarmName", "Unknown Alarm")
    alarm_description = alarm_data.get("AlarmDescription", "No description")
    new_state = alarm_data.get("NewStateValue", "UNKNOWN")
    old_state = alarm_data.get("OldStateValue", "UNKNOWN")
    reason = alarm_data.get("NewStateReason", "No reason provided")
    timestamp = alarm_data.get("StateChangeTime", datetime.utcnow().isoformat())
    region = alarm_data.get("Region", "us-east-1")
    namespace = alarm_data.get("Trigger", {}).get("Namespace", "Unknown")
    metric_name = alarm_data.get("Trigger", {}).get("MetricName", "Unknown")

    # Build context for Claude
    incident_context = f"""
CloudWatch Alarm Triggered:

- **Alarm Name**: {alarm_name}
- **Description**: {alarm_description}
- **State Change**: {old_state} → {new_state}
- **Reason**: {reason}
- **Timestamp**: {timestamp}
- **Region**: {region}
- **Namespace**: {namespace}
- **Metric**: {metric_name}

Full alarm data:
```json
{json.dumps(alarm_data, indent=2)}
```

Please analyze this incident and provide your assessment.
"""

    print(f"Analyzing incident: {alarm_name}")

    try:
        # Call Claude for analysis
        analysis = invoke_claude(
            model_id=CLAUDE_MODEL,
            system=SYSTEM_PROMPT,
            user=incident_context
        )

        print(f"Claude analysis:\n{analysis}")

        # Build incident report
        report = build_incident_report(
            alarm_name=alarm_name,
            new_state=new_state,
            timestamp=timestamp,
            analysis=analysis
        )

        # Publish to SNS if configured
        if SNS_TOPIC_ARN:
            publish_report(report, alarm_name)

        return report

    except Exception as e:
        error_msg = f"Error analyzing incident: {str(e)}"
        print(error_msg)
        # Still try to send basic notification
        if SNS_TOPIC_ARN:
            publish_report(f"Incident: {alarm_name}\nState: {new_state}\n\nError generating AI analysis: {str(e)}", alarm_name)
        raise


def build_incident_report(alarm_name: str, new_state: str, timestamp: str, analysis: str) -> str:
    """Build formatted incident report."""
    state_emoji = "🔴" if new_state == "ALARM" else "🟢" if new_state == "OK" else "🟡"

    report = f"""
{'='*60}
{state_emoji} INCIDENT REPORT - {new_state}
{'='*60}

📋 Alarm: {alarm_name}
🕐 Time: {timestamp}
📊 State: {new_state}

{'─'*60}
🤖 AI ANALYSIS (Claude)
{'─'*60}

{analysis}

{'='*60}
Generated by Vandelay Industries Incident Reporter
{'='*60}
"""
    return report


def publish_report(report: str, alarm_name: str):
    """Publish incident report to SNS."""
    try:
        sns.publish(
            TopicArn=SNS_TOPIC_ARN,
            Subject=f"[Incident Report] {alarm_name}",
            Message=report
        )
        print(f"Published report to SNS: {SNS_TOPIC_ARN}")
    except Exception as e:
        print(f"Failed to publish to SNS: {str(e)}")
        raise
